Feature/internal link #104
lern-edu/lern pull request #123
Opened 2018-03-08 18:09 UTC by andredornas

@deleuterio nao sei se conclui, mas acho que ta usável já

2018-03-09 13:22 UTC, deleuterio requested changes
Tive que dar rebase no branch.... Mas está funcionando legal para cirar, o show que não sei se está funcionando, pois sempre que crio uma tag com description e tento ver aquele dialog de tags ele sempre está vazio.

2018-03-09 20:54 UTC, andredornas commented
@deleuterio as tags filhas usam a descrição da tag pai? aqui ta aparecendo certo a tag que cria com descrição, as filhas aparecem em branco mesmo...

2018-03-10 02:53 UTC, deleuterio commented
Não não, cada uma das tags tem sua descrição. Provável que isso acontaça pelo bug de inserir conteúdo.

2018-03-10 02:53 UTC, deleuterio commented
Vamos resolver esses bugfixies e mergir nesse branch e ver se resolve

2018-03-13 02:47 UTC, deleuterio approved these changes

2018-03-16 01:01 UTC, merged

2018-03-16 01:01 UTC, andredornas commented
@deleuterio essa PR tava fechada mas sem mergir. Mergi ela agora, tem problema?