Feature/delete content #134
lern-edu/lern pull request #144
Opened 2018-03-11 22:48 UTC by andredornas

@deleuterio implementei a remoção de tags e testes, mas sem verificar dependencia, que temos que ver como fazer.. pode remover uma tag que ja ta em um teste?

2018-03-12 12:11 UTC, deleuterio submitted a review, later dismissed

2018-03-12 12:16 UTC, deleuterio requested changes
Ao remover uma tag pai, o campo parent das tags filhas dessa tag devem ser setados como null. Tem como criar um hook no astronomy para isso (acho melhor assim) ou no próprio método de delete tag dar update nas tags filhas.

Vai ser bom também colocar um confirm perguntando se realmente quer deletar aquela tag...

2018-03-13 00:15 UTC, andredornas commented
opa, verdadeeeeee. Me esqueci disso ai tambem, vou implementar! O confirm eu já coloquei, nao deu ai nao?

2018-03-13 00:37 UTC, andredornas commented
@deleuterio é uma boa copiar a description pros filhos?

2018-03-13 02:28 UTC, deleuterio commented
Oh, confim foi vacilo meu :trollface: 
Agora copiar description deixa pra lá, melhor não...

2018-03-13 02:28 UTC, deleuterio approved these changes

2018-03-13 02:28 UTC, merged