Feature/enrollment screen #149
lern-edu/lern pull request #169
Opened 2018-03-18 15:57 UTC by andredornas

2018-03-21 10:49 UTC, deleuterio commented on client/views/Public/Login/Enroll.jsx
> +  handleSubmit = () => {
Acho que esse fluxo terá que ser diferente...

2018-03-21 10:56 UTC, deleuterio requested changes

2018-03-21 10:56 UTC, deleuterio commented on client/views/Public/Login/Enroll.jsx
> +  handleRedirect = () => {
Esse handle redirect vai retornar a tela de login, e junto vai invocar o [`Accounts.sendEnrollmentEmail`](https://docs.meteor.com/api/passwords.html#Accounts-sendEnrollmentEmail) para enviar um email de set password para o user.

2018-03-21 10:56 UTC, deleuterio commented on client/views/Public/Login/Enroll.jsx
> +  handleRedirect = () => {
Também será necessário configurar [`Accounts.onEnrollmentLink`](https://docs.meteor.com/api/passwords.html#Accounts-onEnrollmentLink) no init.js semelhante a configuração de `onResetPasswordLink`.

2018-03-21 10:57 UTC, deleuterio commented
O problema de deixar assim é que além de qualquer um cadastrar com qualquer email, se o cara coloca um email errado que não existe nunca vai conseguir recuperar a senha...

2018-03-21 14:16 UTC, andredornas commented
Verdade. Farei as alterações!!

2018-03-25 15:21 UTC, andredornas commented
@deleuterio nao fiz com o enrollmentEmail, usei o vericationEmail e uma tela pra impedir que ele acesse sem ter um email verificado....

2018-03-28 06:27 UTC, deleuterio approved these changes

2018-03-28 06:27 UTC, merged