Feature/timeouts #160
lern-edu/lern pull request #178
Opened 2018-04-02 02:51 UTC by andredornas

2018-04-03 11:28 UTC, deleuterio requested changes
Só um pequeno detalhe para essa feature :)

2018-04-03 11:28 UTC, deleuterio commented on packages/lern-methods/server/student/tests.js
> +    attempt.pages[newPage].set('startedAt', new Date());
:warning: Mesmo quando crio um teste com timeout none ele coloca um timeout no test.

2018-04-03 11:28 UTC, deleuterio commented on packages/lern-model/collections/tests/schema.js
> +      /*immutable: true,*/
:wrench: Não sei se está difícil... mas tem como colocar o timeout per page diferente para cada page?

2018-04-03 11:47 UTC, andredornas commented on packages/lern-methods/server/student/tests.js
> +    attempt.pages[newPage].set('startedAt', new Date());
opa, falha minha! esqueci de veirifcar quando é none 😢

2018-04-03 11:50 UTC, andredornas commented on packages/lern-model/collections/tests/schema.js
> +      /*immutable: true,*/
acho que rola sim... voce pensou passando o campo de time pra page ou armazenando um array de tempos? e outra coisa, acho que isso vai implicar mudança na forma de criar os testes... pode ser uma nova issue isso depois

2018-04-04 10:10 UTC, deleuterio approved these changes

2018-04-04 10:11 UTC, merged