Bugfix/Request email on register #78
lern-edu/lern pull request #84
Opened 2018-01-26 13:43 UTC by andredornas

2018-01-26 15:42 UTC, deleuterio approved these changes

2018-01-28 00:58 UTC, deleuterio requested changes

2018-01-28 00:58 UTC, deleuterio commented on packages/lern-layouts/components/Safe.jsx
> +    if (user) {
Acho que esse Hook aqui não tá acontecendo legal... Minha sugestão é que ele aconteça no método `GetInitialRoute`, se o user não tiver email, a rota inicial será `PublicLogin`.
Eu não consegui fazer funcionar aqui, sempre que faço login por FB ou G+ ele aparece o snack de bem vindo e me alerta que a rota student home route não existe.

2018-01-28 00:58 UTC, deleuterio commented on client/views/Public/Complete/View.jsx
> +              onKeyDown={this.handlePressEnter.bind(this)}
Aprendi uma coisa legal sobre ES6... `this.handlePressEnter` não precisa de bindar this se na linha [37](https://github.com/lern-edu/lern/pull/84/files#diff-8b38b75d0514f7c9623dc55217debafeR37) a função for declarada assim:
```js
handlePressEnter = (event) => {
     if (event.keyCode == 13) _.bind(this.handleSubmit, this)();
}
```
Ela também pode ser declarada como ES5, assim a função se torna unscoped também

2018-01-28 01:13 UTC, andredornas commented on packages/lern-layouts/components/Safe.jsx
> +    if (user) {
Pois é, eu testei colocando no `GetInitalRoute` ele redireciona certo na primeira vez, mas se o cara mexer na url, ele continua sem email normalmente...

2018-01-28 01:18 UTC, deleuterio commented on packages/lern-layouts/components/Safe.jsx
> +    if (user) {
Hum, é verdade, não lembrei desse problema...

2018-02-02 02:11 UTC, deleuterio approved these changes
Eu revisei o código local e tudo funcionou.
Apenas desabilitei o hook de login para pegar email do Facebook que pode ser um email pouco usado.

2018-02-02 12:11 UTC, merged