Feature/dashboard report #76
lern-edu/lern pull request #86
Opened 2018-01-28 01:07 UTC by deleuterio

Primeira versão para reports e funcionamento de locales do i18n implantado.
Dados para teste de report:
```json
[
  {
   name: 'Core competencies',
   score: 5,
   childrens: [
     {
       name: 'Memorization',
       color: '#d50000',
       score: 2
     }, {
       name: 'Attention',
       color: '#aa00ff',
       score: 5
     }, {
       name: 'Concentration',
       color: '#304ffe',
       score: 7
     }, {
       name: 'Focus',
       color: '#00b8d4',
       score: 0
     }, {
       name: 'Persistence',
       color: '#00c853',
       score: 4
     }, {
       name: 'Self discipline',
       color: '#3e2723',
       score: 1
     }, {
       name: 'Flexibility',
       color: '#0091ea',
       score: 3
     }, {
       name: 'Curiosity',
       color: '#ffd600',
       score: 8
     }, {
       name: 'Interest',
       color: '#aeea00',
       score: 0
     }
   ]
  }
]
    
```

2018-02-01 13:44 UTC, andredornas requested changes

2018-02-01 13:44 UTC, andredornas commented on client/views/Student/Report/Chart.jsx
> +import Chart from 'chart.js';
Ta dando erro ao importar isso. Aqui voce inclui chart.js e no package.json inclui chartjs.

2018-02-01 13:44 UTC, andredornas commented on package.json
> +    "chartjs": "^0.3.24",
Aqui é chartjs ou charts.js??

2018-02-01 14:01 UTC, deleuterio commented on package.json
> +    "chartjs": "^0.3.24",
Putz, aqui que eu errei, a lib é `chart.js`

2018-02-01 17:56 UTC, andredornas requested changes

2018-02-01 17:56 UTC, andredornas commented on client/views/Student/Report/View.jsx
> +import LinearProgress from 'material-ui/Progress'
import { LinearProgress } from 'material-ui/Progress';

2018-02-02 01:38 UTC, deleuterio commented on client/views/Student/Report/View.jsx
> +import LinearProgress from 'material-ui/Progress'
Done!

2018-02-02 01:38 UTC, deleuterio commented on client/views/Student/Report/Chart.jsx
> +import Chart from 'chart.js';
Done

2018-02-02 01:46 UTC, merged